#!/bin/bash
# mac-triage installer.
#
# Usage:
#   sudo bash install-mac-triage.sh                 install or upgrade
#   bash install-mac-triage.sh --extract-only DIR   write the files that would be
#                                                   installed into DIR and exit
#                                                   (no root needed, for auditing)
#   bash install-mac-triage.sh --version
#
# This file is generated by scripts/build.sh from src/. Do not edit dist/ copies.
MT_VERSION="@VERSION@"
ROOT="/usr/local/mac-triage"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"

# Each payload file is written with put_file <relative path> from a heredoc.
put_file(){
  local dest="$STAGE/$1"
  mkdir -p "$(dirname "$dest")" || exit 1
  cat > "$dest" || exit 1
}

stage_payload(){
# @@PAYLOAD@@
:
}

case "${1:-}" in
  --version) echo "mac-triage installer $MT_VERSION"; exit 0;;
  --extract-only)
    [ -n "${2:-}" ] || { echo "Usage: $0 --extract-only DIR"; exit 2; }
    STAGE="$2"; mkdir -p "$STAGE" || exit 1
    stage_payload; echo "Extracted mac-triage $MT_VERSION into $STAGE"; exit 0;;
  "") ;;
  *) echo "Unknown option: $1"; exit 2;;
esac

[ "$EUID" -eq 0 ] || { echo "Please run: sudo bash $0"; exit 1; }
U="${SUDO_USER:-}"
if [ -z "$U" ] || [ "$U" = root ]; then echo "Run this from your normal account using sudo."; exit 1; fi
case "$U" in *[!A-Za-z0-9._-]*) echo "Unsupported user name: $U"; exit 1;; esac
[ "$(id -u "$U" 2>/dev/null || echo 0)" -ge 500 ] || { echo "$U is not a normal user account."; exit 1; }
# Home folder paths can contain spaces, so take everything after the label.
UH=$(dscl . -read "/Users/$U" NFSHomeDirectory 2>/dev/null | sed -n 's/^NFSHomeDirectory: //p' | head -1)
[ -d "$UH" ] || { echo "Could not find the home folder of $U."; exit 1; }

# Root will run these files on a schedule. Every folder on the way to them must be
# owned by root and writable only by root, or a normal process could swap them out.
safe_dir(){
  local d="$1" o m
  [ -L "$d" ] && { echo "Refusing to install: $d is a symlink."; return 1; }
  [ -e "$d" ] || return 0
  o=$(stat -f '%u' "$d"); m=$(stat -f '%Lp' "$d")
  [ "$o" = 0 ] || { echo "Refusing to install: $d is not owned by root."; return 1; }
  case "$m" in *[2367]?|*?[2367]) echo "Refusing to install: $d is writable by group or others (mode $m)."; return 1;; esac
  return 0
}
for d in /usr /usr/local "$ROOT" "$ROOT/core" "$ROOT/modules" "$ROOT/bin" /Library/LaunchDaemons; do safe_dir "$d" || exit 1; done
if [ -d /usr/local/bin ] && [ "$(stat -f '%u' /usr/local/bin)" != 0 ]; then
  echo "    Note: /usr/local/bin is not owned by root, so the 'macscan' link there could be replaced"
  echo "    by another program. You can always run $ROOT/macscan directly."
fi
echo "==> Installing mac-triage $MT_VERSION for $U into $ROOT"

STAGE=$(mktemp -d /private/var/tmp/mactriage-install.XXXXXX) || exit 1
trap 'rm -rf "$STAGE"' EXIT
stage_payload

launchctl bootout system/com.mactriage.auto 2>/dev/null
launchctl bootout system/com.mactriage.runner 2>/dev/null

# Old 1.x versions added a shell function to .zshrc. Remove it as the user (not as root).
if sudo -u "$U" grep -q "# >>> mac-triage >>>" "$UH/.zshrc" 2>/dev/null; then
  sudo -u "$U" sed -i '' '/# >>> mac-triage >>>/,/# <<< mac-triage <<</d' "$UH/.zshrc"
  echo "==> Removed the old macscan function from .zshrc"
fi

umask 022
mkdir -p "$ROOT/bin" "$ROOT/rules"
[ -d "$ROOT/state" ] || mkdir -m 700 "$ROOT/state"; chmod 700 "$ROOT/state"; mkdir -p "$ROOT/state/inv"
# Replace code folders completely so files removed in this version do not linger.
rm -rf "$ROOT/core" "$ROOT/modules" "$ROOT/helper" "$ROOT/src"
( cd "$STAGE" && find . -type f ) | while IFS= read -r f; do
  f="${f#./}"; mkdir -p "$ROOT/$(dirname "$f")"; cp "$STAGE/$f" "$ROOT/$f"
done

############################################################ CONFIG
if [ ! -f "$ROOT/config" ]; then
cat > "$ROOT/config" <<EOF_CONFIG
# mac-triage settings. Change with: macscan --set KEY=VALUE
TARGET_USER="$U"
REPORT_DIR="$UH/Documents/mac-triage-reports"
KEEP_REPORTS="4"
MAX_AGE_DAYS="30"
LOOKBACK_DAYS="60"
AUTO="on"
AUTO_INTERVAL_DAYS="7"
AUTO_ON_NEW_APP="yes"
AUTO_MIN_BATTERY="30"
ONLY_IF_FINDINGS="no"
NOTIFY="yes"
ZIP="yes"
YARA="yes"
CLAMAV="yes"
CLAMAV_SCOPE="standard"
EOF_CONFIG
fi
sed -i '' "s|^TARGET_USER=.*|TARGET_USER=\"$U\"|" "$ROOT/config"

############################################################ BUILD, PERMISSIONS, SERVICES
echo "==> Compiling the Full Disk Access helper"
if clang -O2 -Wall -o "$ROOT/bin/macscan-helper" "$ROOT/helper/macscan-helper.c" 2>"$STAGE/clang.err"; then
  codesign -f -s - -i com.mactriage.helper "$ROOT/bin/macscan-helper" >/dev/null 2>&1
  echo "    ok"
else
  echo "    WARNING: compile failed:"; head -20 "$STAGE/clang.err" | sed 's/^/      /'
  echo "    If it mentions the Xcode license: sudo xcodebuild -license accept, then run this installer again."
  rm -f "$ROOT/bin/macscan-helper"
fi

chown -R root:wheel "$ROOT"
find "$ROOT" -path "$ROOT/state" -prune -o -type d -exec chmod 755 {} +
find "$ROOT" -path "$ROOT/state" -prune -o -type f -exec chmod 644 {} +
chmod 755 "$ROOT/macscan" "$ROOT/core/run.sh" "$ROOT"/modules/*.sh
[ -f "$ROOT/bin/macscan-helper" ] && chmod 755 "$ROOT/bin/macscan-helper"
chmod -R go-rwx "$ROOT/state"
mkdir -p /usr/local/bin && ln -sf "$ROOT/macscan" /usr/local/bin/macscan

BREW=/opt/homebrew/bin/brew
if [ -x "$BREW" ]; then
  echo "==> Installing YARA and ClamAV with Homebrew (as $U)"
  sudo -u "$U" -H "$BREW" install yara clamav || echo "    WARNING: Homebrew install had problems; YARA/ClamAV modules will skip if missing."
  CONF=/opt/homebrew/etc/clamav
  if [ -f "$CONF/freshclam.conf.sample" ] && [ ! -f "$CONF/freshclam.conf" ]; then
    sudo -u "$U" /bin/sh -c "sed 's/^Example/#Example/' '$CONF/freshclam.conf.sample' > '$CONF/freshclam.conf'"
  fi
  sudo -u "$U" mkdir -p /opt/homebrew/var/lib/clamav
else
  echo "==> Homebrew not found, skipping YARA and ClamAV"
fi

echo "==> Downloading YARA rules and ClamAV signatures (a few minutes)"
/bin/bash "$ROOT/core/run.sh" --task update-rules
echo "==> Installing the scan service and automatic scans"
"$ROOT/macscan" --install-services

cat <<EOF_DONE

==============================================================
 mac-triage $MT_VERSION installed.

 LAST STEP: give the scanner Full Disk Access.
 System Settings and a Finder window are opening now.
 Drag "macscan-helper" from Finder into the Full Disk Access
 list and make sure its switch is ON.

 Then run:
   macscan --check-fda
   macscan
==============================================================
EOF_DONE
sudo -u "$U" open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null
[ -f "$ROOT/bin/macscan-helper" ] && sudo -u "$U" open -R "$ROOT/bin/macscan-helper" 2>/dev/null
