#!/bin/bash
# mac-triage installer.
#
# Usage (see --help):
#   sudo bash install-mac-triage.sh                  install, or upgrade an existing install
#   sudo bash install-mac-triage.sh --uninstall      remove it (reports are kept)
#   bash install-mac-triage.sh --extract-only DIR    write the files that would be installed
#                                                    into DIR and exit (no root, for auditing)
#
# This file is generated by scripts/build.sh from src/. Do not edit dist/ copies.
MT_VERSION="@VERSION@"
ROOT="/usr/local/mac-triage"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin"

# Each payload file is written with put_file <relative path> from a heredoc.
put_file(){
  local dest="$STAGE/$1"
  mkdir -p "$(dirname "$dest")" || exit 1
  cat > "$dest" || exit 1
}

stage_payload(){
# @@PAYLOAD@@
:
}

usage(){ cat <<'USAGE'
mac-triage installer

  sudo bash install-mac-triage.sh                    install, or upgrade an existing install
  sudo bash install-mac-triage.sh --allow-downgrade  install an older version over a newer one
  sudo bash install-mac-triage.sh --uninstall        remove mac-triage (reports are kept)
  bash install-mac-triage.sh --extract-only DIR      write the files that would be installed into DIR
  bash install-mac-triage.sh --version | --help

Upgrading keeps your settings, scan history, acknowledged flags, YARA rules and reports.
New settings are added with their defaults. Full Disk Access stays valid unless the
helper program itself changed, and the installer tells you when it did.
USAGE
}

# version_cmp A B: prints -1, 0 or 1 (semantic versions, missing parts count as 0).
version_cmp(){
  local a="$1" b="$2" x y i
  for i in 1 2 3; do
    x=$(printf '%s' "$a" | cut -d. -f"$i"); y=$(printf '%s' "$b" | cut -d. -f"$i")
    x=${x%%[!0-9]*}; y=${y%%[!0-9]*}; x=${x:-0}; y=${y:-0}
    [ "$x" -lt "$y" ] && { echo -1; return; }
    [ "$x" -gt "$y" ] && { echo 1; return; }
  done
  echo 0
}

installed_version(){ tr -d '[:space:]' < "$ROOT/VERSION" 2>/dev/null || echo ""; }

# default_config: the settings a new install starts with (uses U and UH).
default_config(){
  cat <<EOF_CONFIG
TARGET_USER="$U"
REPORT_DIR="$UH/Documents/mac-triage-reports"
KEEP_REPORTS="4"
MAX_AGE_DAYS="30"
LOOKBACK_DAYS="60"
AUTO="on"
AUTO_INTERVAL_DAYS="7"
AUTO_ON_NEW_APP="yes"
AUTO_MIN_BATTERY="30"
ONLY_IF_FINDINGS="no"
NOTIFY="yes"
ZIP="yes"
YARA="yes"
CLAMAV="yes"
CLAMAV_SCOPE="standard"
INCLUDE_TRASH="no"
SUPPLY_CHAIN="no"
EXEC_MONITOR="no"
EOF_CONFIG
}

# config_write <file>: creates the config, or adds settings it does not have yet.
# Existing values are never changed. Prints the names of added settings.
config_write(){
  local f="$1" line k
  if [ ! -f "$f" ]; then
    { echo "# mac-triage settings. Change with: macscan --set KEY=VALUE"; default_config; } > "$f"
    return 0
  fi
  default_config | while IFS= read -r line; do
    k="${line%%=*}"
    grep -q "^$k=" "$f" || { echo "$line" >> "$f"; echo "$k"; }
  done
}

# helper_needs_build <new helper source>: true unless the installed helper was built
# from exactly this source. Keeping the binary keeps its code signature, so the Full
# Disk Access permission stays valid across upgrades.
helper_needs_build(){
  [ -x "$ROOT/bin/macscan-helper" ] || return 0
  [ -f "$ROOT/helper/macscan-helper.c" ] || return 0
  cmp -s "$1" "$ROOT/helper/macscan-helper.c" && return 1
  return 0
}

scan_running(){
  local p; p=$(cat "$ROOT/state/running.pid" 2>/dev/null)
  [ -n "$p" ] && kill -0 "$p" 2>/dev/null
}

# Root will run these files on a schedule. Every folder on the way to them must be
# owned by root and writable only by root, or a normal process could swap them out.
safe_dir(){
  local d="$1" o m
  [ -L "$d" ] && { echo "Refusing to install: $d is a symlink."; return 1; }
  [ -e "$d" ] || return 0
  o=$(stat -f '%u' "$d"); m=$(stat -f '%Lp' "$d")
  [ "$o" = 0 ] || { echo "Refusing to install: $d is not owned by root."; return 1; }
  case "$m" in *[2367]?|*?[2367]) echo "Refusing to install: $d is writable by group or others (mode $m)."; return 1;; esac
  return 0
}

main(){
  local downgrade=no
  case "${1:-}" in
    --version) echo "mac-triage installer $MT_VERSION"; return 0;;
    -h|--help) usage; return 0;;
    --extract-only)
      [ -n "${2:-}" ] || { echo "Usage: $0 --extract-only DIR"; return 2; }
      STAGE="$2"; mkdir -p "$STAGE" || return 1
      stage_payload; echo "Extracted mac-triage $MT_VERSION into $STAGE"; return 0;;
    --uninstall)
      [ "$EUID" -eq 0 ] || { echo "Please run: sudo bash $0 --uninstall"; return 1; }
      [ -x "$ROOT/macscan" ] || { echo "mac-triage is not installed."; return 0; }
      "$ROOT/macscan" --uninstall; return;;
    --allow-downgrade) downgrade=yes;;
    "") ;;
    *) echo "Unknown option: $1"; usage; return 2;;
  esac

  [ "$EUID" -eq 0 ] || { echo "Please run: sudo bash $0"; return 1; }
  U="${SUDO_USER:-}"
  if [ -z "$U" ] || [ "$U" = root ]; then echo "Run this from your normal account using sudo."; return 1; fi
  case "$U" in *[!A-Za-z0-9._-]*) echo "Unsupported user name: $U"; return 1;; esac
  [ "$(id -u "$U" 2>/dev/null || echo 0)" -ge 500 ] || { echo "$U is not a normal user account."; return 1; }
  # Home folder paths can contain spaces, so take everything after the label.
  UH=$(dscl . -read "/Users/$U" NFSHomeDirectory 2>/dev/null | sed -n 's/^NFSHomeDirectory: //p' | head -1)
  [ -d "$UH" ] || { echo "Could not find the home folder of $U."; return 1; }

  local d
  for d in /usr /usr/local "$ROOT" "$ROOT/core" "$ROOT/modules" "$ROOT/bin" /Library/LaunchDaemons; do safe_dir "$d" || return 1; done
  if [ -d /usr/local/bin ] && [ "$(stat -f '%u' /usr/local/bin)" != 0 ]; then
    echo "    Note: /usr/local/bin is not owned by root, so the 'macscan' link there could be replaced"
    echo "    by another program. You can always run $ROOT/macscan directly."
  fi

  # Fresh install, upgrade, repair or downgrade?
  local old mode
  old=$(installed_version)
  if [ -z "$old" ]; then mode=install
  else
    case "$(version_cmp "$MT_VERSION" "$old")" in
      1) mode=upgrade;;
      0) mode=repair;;
      -1) if [ "$downgrade" = yes ]; then mode=downgrade
          else
            echo "mac-triage $old is installed, which is newer than this installer ($MT_VERSION)."
            echo "Nothing was changed. To install the older version anyway: sudo bash $0 --allow-downgrade"
            return 1
          fi;;
    esac
  fi
  if scan_running; then
    echo "A scan is running right now. Nothing was changed."
    echo "Wait for it to finish (macscan --status), or stop it with: macscan --stop. Then run the installer again."
    return 1
  fi
  case "$mode" in
    install) echo "==> Installing mac-triage $MT_VERSION for $U into $ROOT";;
    upgrade) echo "==> Upgrading mac-triage $old -> $MT_VERSION (your settings, history and reports are kept)";;
    repair) echo "==> Reinstalling mac-triage $MT_VERSION (repair; your settings, history and reports are kept)";;
    downgrade) echo "==> Downgrading mac-triage $old -> $MT_VERSION (your settings, history and reports are kept)";;
  esac

  STAGE=$(mktemp -d /private/var/tmp/mactriage-install.XXXXXX) || return 1
  trap 'rm -rf "$STAGE"' EXIT
  stage_payload

  launchctl bootout system/com.mactriage.auto 2>/dev/null
  launchctl bootout system/com.mactriage.runner 2>/dev/null

  # Old 1.x versions added a shell function to .zshrc. Remove it as the user (not as root).
  if sudo -u "$U" grep -q "# >>> mac-triage >>>" "$UH/.zshrc" 2>/dev/null; then
    sudo -u "$U" sed -i '' '/# >>> mac-triage >>>/,/# <<< mac-triage <<</d' "$UH/.zshrc"
    echo "==> Removed the old macscan function from .zshrc"
  fi

  local build_helper=no
  helper_needs_build "$STAGE/helper/macscan-helper.c" && build_helper=yes

  umask 022
  mkdir -p "$ROOT/bin" "$ROOT/rules"
  [ -d "$ROOT/state" ] || mkdir -m 700 "$ROOT/state"; chmod 700 "$ROOT/state"; mkdir -p "$ROOT/state/inv"
  # Replace code folders completely so files removed in this version do not linger.
  rm -rf "$ROOT/core" "$ROOT/modules" "$ROOT/helper" "$ROOT/src"
  ( cd "$STAGE" && find . -type f ) | while IFS= read -r f; do
    f="${f#./}"; mkdir -p "$ROOT/$(dirname "$f")"; cp "$STAGE/$f" "$ROOT/$f"
  done

  local added
  added=$(config_write "$ROOT/config" | tr '\n' ' ')
  sed -i '' "s|^TARGET_USER=.*|TARGET_USER=\"$U\"|" "$ROOT/config"
  [ -n "$added" ] && echo "==> New settings added with their defaults: $added(see macscan --config)"

  local fda_needed=no
  if [ "$build_helper" = yes ]; then
    echo "==> Compiling the Full Disk Access helper"
    if clang -O2 -Wall -o "$ROOT/bin/macscan-helper" "$ROOT/helper/macscan-helper.c" 2>"$STAGE/clang.err"; then
      codesign -f -s - -i com.mactriage.helper "$ROOT/bin/macscan-helper" >/dev/null 2>&1
      echo "    ok"; fda_needed=yes
    else
      echo "    WARNING: compile failed:"; head -20 "$STAGE/clang.err" | sed 's/^/      /'
      echo "    If it mentions the Xcode license: sudo xcodebuild -license accept, then run this installer again."
      rm -f "$ROOT/bin/macscan-helper"
    fi
  else
    echo "==> Full Disk Access helper unchanged; kept as is, so its permission stays valid"
  fi

  chown -R root:wheel "$ROOT"
  find "$ROOT" -path "$ROOT/state" -prune -o -type d -exec chmod 755 {} +
  find "$ROOT" -path "$ROOT/state" -prune -o -type f -exec chmod 644 {} +
  chmod 755 "$ROOT/macscan" "$ROOT/core/run.sh" "$ROOT"/modules/*.sh
  [ -f "$ROOT/bin/macscan-helper" ] && chmod 755 "$ROOT/bin/macscan-helper"
  chmod -R go-rwx "$ROOT/state"
  # Record what was installed, so every scan can tell if a shipped file changed.
  # shellcheck source=../core/lib/integrity.sh
  source "$ROOT/core/lib/integrity.sh"
  integrity_manifest "$ROOT" > "$ROOT/manifest.sha256"; chown root:wheel "$ROOT/manifest.sha256"; chmod 644 "$ROOT/manifest.sha256"
  mkdir -p /usr/local/bin && ln -sf "$ROOT/macscan" /usr/local/bin/macscan

  local BREW=/opt/homebrew/bin/brew CONF=/opt/homebrew/etc/clamav
  if [ -x /opt/homebrew/bin/yara ] && [ -x /opt/homebrew/bin/clamscan ]; then
    echo "==> YARA and ClamAV already installed"
  elif [ -x "$BREW" ]; then
    echo "==> Installing YARA and ClamAV with Homebrew (as $U)"
    sudo -u "$U" -H "$BREW" install yara clamav || echo "    WARNING: Homebrew install had problems; YARA/ClamAV modules will skip if missing."
    if [ -f "$CONF/freshclam.conf.sample" ] && [ ! -f "$CONF/freshclam.conf" ]; then
      sudo -u "$U" /bin/sh -c "sed 's/^Example/#Example/' '$CONF/freshclam.conf.sample' > '$CONF/freshclam.conf'"
    fi
    sudo -u "$U" mkdir -p /opt/homebrew/var/lib/clamav
  else
    echo "==> Homebrew not found, skipping YARA and ClamAV"
  fi

  if [ -s "$ROOT/rules/all.yarc" ]; then
    echo "==> YARA rules already present (they refresh weekly during scans; now: macscan --update-rules)"
  else
    echo "==> Downloading YARA rules and ClamAV signatures (a few minutes)"
    /bin/bash "$ROOT/core/run.sh" --task update-rules
  fi
  echo "==> Installing the scan service and automatic scans"
  "$ROOT/macscan" --install-services

  echo
  echo "=============================================================="
  case "$mode" in
    install) echo " mac-triage $MT_VERSION installed.";;
    upgrade|downgrade) echo " mac-triage is now $MT_VERSION (was $old).";;
    repair) echo " mac-triage $MT_VERSION reinstalled.";;
  esac
  if [ "$mode" != install ]; then
    echo " Kept: settings, scan history, acknowledged flags, YARA rules, reports."
    echo " What changed: https://github.com/aamir-067/macscan-cli/releases/tag/v$MT_VERSION"
  fi
  if [ "$fda_needed" = yes ]; then
    echo
    echo " ACTION NEEDED: give the scanner Full Disk Access."
    [ "$mode" != install ] && echo " (The helper program changed, so macOS treats it as new.)"
    echo " System Settings and a Finder window are opening now. Drag"
    echo " \"macscan-helper\" into the Full Disk Access list and switch it ON."
    echo
    echo " Then run:  macscan --check-fda   and then   macscan"
  else
    echo " No action needed. Full Disk Access is unchanged."
    echo " Check anytime with: macscan --check-fda"
  fi
  echo "=============================================================="
  if [ "$fda_needed" = yes ]; then
    sudo -u "$U" open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null
    [ -f "$ROOT/bin/macscan-helper" ] && sudo -u "$U" open -R "$ROOT/bin/macscan-helper" 2>/dev/null
  fi
  return 0
}

# Run only when executed, so tests can load the functions above.
if [ "${BASH_SOURCE[0]}" = "$0" ]; then main "$@"; exit $?; fi
